name: MapReflectionAPI
version: '${project.version}'
main: tech.sbdevelopment.mapreflectionapi.MapReflectionAPI
api-version: 1.13
authors: [ inventivetalent, SBDeveloper ]
description: This API helps developer with viewing images on maps or in inventories.
website: https://sbdevelopment.tech
commands:
  mapmanager:
    description: The main command of MapManager.
permissions:
  mapmanager.reload:
    description: Access to /mapmanager reload
    default: op